
<!ELEMENT circuito (
    nombre,
    longitud,
    anchuraMedia,
    fecha,
    horaInicio,
    vueltas,
    localidad,
    pais,
    patrocinador,
    referencias,
    galeriaFotografias,
    galeriaVideos,
    puntoOrigen,
    tramos,
    vencedor,
    clasificados
)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad CDATA #REQUIRED>

<!ELEMENT anchuraMedia (#PCDATA)>
<!ATTLIST anchuraMedia unidad CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)> 
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!-- referencias: al menos 3 referencias -->
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!-- galeriaFotografias: 1..5 fotos -->
<!ELEMENT galeriaFotografias (foto, foto?, foto?, foto?, foto?)>
<!ELEMENT foto (#PCDATA)>

<!-- galeriaVideos: 1..3 videos -->
<!ELEMENT galeriaVideos (video+)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT puntoOrigen (longitudOrigen, latitud, altitud)>
<!ELEMENT longitudOrigen (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadas, numeroSector)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad CDATA #REQUIRED>
<!ELEMENT coordenadas (longitudPunto, latitudPunto, altitudPunto)>
<!ELEMENT longitudPunto (#PCDATA)>
<!ELEMENT latitudPunto (#PCDATA)>
<!ELEMENT altitudPunto (#PCDATA)>
<!ELEMENT numeroSector (#PCDATA)>
<!ELEMENT vencedor (nombrePiloto, tiempo)>
<!ELEMENT nombrePiloto (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT clasificados (primero, segundo, tercero)>
<!ELEMENT primero (#PCDATA)>
<!ELEMENT segundo (#PCDATA)>
<!ELEMENT tercero (#PCDATA)>
