<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="fecha" />
				<xs:element ref="horaInicio" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFotografias" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificados" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />
	<xs:element name="vueltas" type="xs:integer" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="galeriaFotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="foto" />
				<xs:element minOccurs="0" maxOccurs="1" ref="foto" />
				<xs:element minOccurs="0" maxOccurs="1" ref="foto" />
				<xs:element minOccurs="0" maxOccurs="1" ref="foto" />
				<xs:element minOccurs="0" maxOccurs="1" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="puntoOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudOrigen" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudOrigen" type="xs:string" />
	<xs:element name="latitud" type="xs:string" />
	<xs:element name="altitud" type="xs:string" />
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="numeroSector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudPunto" />
				<xs:element ref="latitudPunto" />
				<xs:element ref="altitudPunto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudPunto" type="xs:string" />
	<xs:element name="latitudPunto" type="xs:string" />
	<xs:element name="altitudPunto" type="xs:string" />
	<xs:element name="numeroSector" type="xs:string" />
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombrePiloto" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombrePiloto" type="xs:string" />
	<xs:element name="tiempo" type="xs:string" />
	<xs:element name="clasificados">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="primero" type="xs:string" />
	<xs:element name="segundo" type="xs:string" />
	<xs:element name="tercero" type="xs:string" />
</xs:schema>